Write a Python program to print the NumPy 
version in your system.

In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'D:\\anaconda\\lib\\site-packages\\numpy\\version.py'>


Write a Python program to reverse an array 
(first element becomes last)

In [5]:
a = np.array([1,2,3,4,5])
res = a[::-1]
print(res)

[5 4 3 2 1]


Write a Python program to convert a list and 
tuple into arrays

In [10]:
a = [1,2,3,4,5]
print(type(a))
b = (5,6,7,8)
print(type(b))

<class 'list'>
<class 'tuple'>


In [11]:
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[5 6 7 8]
<class 'numpy.ndarray'>


Write a Python program to find common values 
between two arrays.


In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8])

for i in arr1:
    for j in arr2:
        if i == j:
            print(j)
            break
            


5


Write a Python program compare two arrays 
using numpy

In [20]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([5,6,7,8])
print(f'arr1 > arr2 : {np.greater(arr1,arr2)}')
print(f'arr1 >= arr2 : {np.greater_equal(arr1,arr2)}')
print(f'arr1 < arr2 : {np.less(arr1,arr2)}')
print(f'arr1 <= arr2 : {np.less_equal(arr1,arr2)}')

arr1 > arr2 : [False False False False]
arr1 >= arr2 : [False False False False]
arr1 < arr2 : [ True  True  True  True]
arr1 <= arr2 : [ True  True  True  True]


Write a Python program to change the 
dimension of an array.


In [25]:
arr = np.array([1,2,3,5])
arr.shape = (2,2)
print(arr)

[[1 2]
 [3 5]]


Write a Python program (using numpy) to sum 
of all the multiples of 3 or 5 below 100

In [27]:
a = np.arange(100)
sum1 =0
for i in a :
    if i%3 == 0 or i%5 == 0:
        sum1 += i
print(sum1)
    

2318


Write a Python program to convert a NumPy 
array into Python list structure.

In [28]:
a = np.arange(10)
print(list(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Write a Python program to how to add an extra 
column to a numpy array.


In [31]:
a = np.array([[1,2,3,5] , [6,7,8,9]])
b = np.array([[10],[11]])
print(np.append(a,b , axis =1))


[[ 1  2  3  5 10]
 [ 6  7  8  9 11]]


Write a Python program to check whether the 
numpy array is empty or not.

In [32]:
a = np.array([[1,2,3,5] , [6,7,8,9]])
if a.size == 0:
    print('array is Empty')
else:
    print('Array is non empty')

Array is non empty


Write a Python program to normalize a 3x3 
random matrix.

In [47]:
import warnings
warnings.filterwarnings('ignore')


a = np.random.random((3,3))
print(f'Array:\n {a}')
amin = a.min()
amax = a.max()
print('Normalised Array:')
n= (a-amin)/(amax - a)
print(n)

Array:
 [[0.81173142 0.02364486 0.07252621]
 [0.58811254 0.49750581 0.72578412]
 [0.12743565 0.2291539  0.25829407]]
Normalised Array:
[[       inf 0.         0.0661269 ]
 [2.52423974 1.50802778 8.16941565]
 [0.15167533 0.35275826 0.42398512]]


How to ignore all numpy warnings (not 
recommended)

In [33]:
import warnings
warnings.filterwarnings('ignore')

 How to swap two rows of an array?

In [58]:
a = np.arange(9)
a.shape = (3,3)
print(f'Arrray: \n{a}')
a[[0,1]] = a[[1,0]]
print(f'Array after row swap: \n{a}')

Arrray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after row swap: 
[[3 4 5]
 [0 1 2]
 [6 7 8]]


Compute bootstrapped 95% confidence 
intervals for the mean of a 1D array X (i.e., 
resample the elements of an array with 
replacement N times, compute the mean of 
each sample, and then compute percentiles 
over the means).


Python program to create a random vector of 
size 10 and sort it

In [5]:
a = np.random.random(10)
print(f'Array: \n{a}')
a.sort()
print(f'sorted array: \n{a}')


Array: 
[0.71476827 0.14262826 0.22328618 0.72305498 0.90317352 0.36442567
 0.43820103 0.56368305 0.94825957 0.19883196]
sorted array: 
[0.14262826 0.19883196 0.22328618 0.36442567 0.43820103 0.56368305
 0.71476827 0.72305498 0.90317352 0.94825957]


Write a Python program to check two random 
arrays are equal or not.


In [14]:
a = np.random.random(5)
b = np.random.random(5)
count = 0
for i in a:
    for j in b:
        if i == j:
            count +=1
            
print(a)
print(b)
if count == len(a):
    print('equal')
else:
    print('not equal')
    
#using allclose
print(np.allclose(a,b))

[0.16456404 0.14285314 0.9430692  0.89833577 0.50742252]
[0.52620197 0.7358922  0.63272023 0.08922467 0.95067116]
not equal
False


Write a Python program to add, subtract, 
multiply, divide arguments element-wise.

In [34]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 5 3 0 6 6 9 5 8 7]
[3 6 1 8 4 0 2 6 0 1]
[ 8 11  4  8 10  6 11 11  8  8]
[ 2 -1  2 -8  2  6  7 -1  8  6]
[15 30  3  0 24  0 18 30  0  7]
[1.66666667 0.83333333 3.         0.         1.5               inf
 4.5        0.83333333        inf 7.        ]


Write a Python program to get the dates of 
yesterday, today and tomorrow

In [31]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [32]:
print(f'yesterday :{yesterday}')
print(f'Today: {today}')
print(f'Tomorrow: {tomorrow}')

yesterday :2022-03-10
Today: 2022-03-11
Tomorrow: 2022-03-12
