In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [4]:
iris = datasets.load_iris()

# creating x and y data
x = iris.data
y= iris.target

sc = StandardScaler()
x_std = sc.fit_transform(x)



#splitting the data
x_train,x_test,y_train,y_test = train_test_split(x_std,y,test_size=0.7,random_state=101)

In [5]:
print(x_train)


[[ 5.53333275e-01  5.58610819e-01  5.35408562e-01  5.27406285e-01]
 [ 1.28034050e+00  9.82172869e-02  6.49083415e-01  3.95774101e-01]
 [ 1.03800476e+00  5.58610819e-01  1.10378283e+00  1.18556721e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [ 1.28034050e+00  9.82172869e-02  9.33270550e-01  1.18556721e+00]
 [-7.79513300e-01  7.88807586e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.73673948e-01 -5.92373012e-01  1.94384000e-01  1.32509732e-01]
 [ 5.53333275e-01 -5.92373012e-01  7.62758269e-01  3.95774101e-01]
 [-4.16009689e-01  1.01900435e+00 -1.39706395e+00 -1.31544430e+00]
 [ 1.89829664e-01 -1.97355361e+00  1.37546573e-01 -2.62386821e-01]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [ 1.03800476e+00  9.82172869e-02  1.04694540e+00  1.58046376e+00]
 [ 3.10997534e-01 -5.92373012e-01  5.35408562e-01  8.77547895e-04]
 [ 2.12851559e+00 -1.31979479e-01  1.61531967e+00  1.18556721e+00]
 [-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e

In [6]:
#creating the model using Perceptron 

per_model = Perceptron(random_state=101)
per_model.fit(x_train,y_train)


Perceptron(random_state=101)

In [7]:
#predicting the model

y_pred_train = per_model.predict(x_train)
y_pred_test = per_model.predict(x_test)

In [9]:
#accuracy_score,confusion_matrix,classification_report

print(classification_report(y_train,y_pred_train))
print('****'*20)
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.86      0.75      0.80        16
           2       0.84      0.94      0.89        17

    accuracy                           0.87        45
   macro avg       0.87      0.87      0.87        45
weighted avg       0.87      0.87      0.86        45

********************************************************************************
              precision    recall  f1-score   support

           0       0.96      0.68      0.80        38
           1       0.60      0.82      0.69        34
           2       0.84      0.79      0.81        33

    accuracy                           0.76       105
   macro avg       0.80      0.77      0.77       105
weighted avg       0.81      0.76      0.77       105



In [10]:
print(confusion_matrix(y_train,y_pred_train))
print('****'*20)
print(confusion_matrix(y_test,y_pred_test))

[[11  1  0]
 [ 1 12  3]
 [ 0  1 16]]
********************************************************************************
[[26 12  0]
 [ 1 28  5]
 [ 0  7 26]]


In [11]:
print(accuracy_score(y_train,y_pred_train))
print('****'*20)
print(accuracy_score(y_test,y_pred_test))

0.8666666666666667
********************************************************************************
0.7619047619047619


In [14]:
# K-fold

from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(per_model,x_test,y_test,cv = 10)
accuracy.mean()

0.7827272727272727